apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultstaticsecret-sample
  namespace: openshift-operators
spec:
  destination:
    create: true
    name: webappconfig
    overwrite: false
    transformation: {}
  hmacSecretData: true
  mount: kvv2
  path: webapp/config
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: openshift-operators/vault-k8socp-com
