apiVersion: v1
data:
  init-script.sh: |-
    #!/bin/bash
    set -e
    sleep 10
    export VAULT_ADDR=http://vault-server-unseal.vault-server-unseal:8200
    if [ "$MY_POD_NAME" == "vault-server-unseal-0" ] 
    then
      vault operator init -status || vault operator init >> /vault/data/init.txt
    fi
    sleep infinity
immutable: false
kind: ConfigMap
metadata:
  name: init-script
  namespace: vault-server-unseal
